version: 0.2

phases:
  install:
    commands:
      - yum install -y zip
  pre_build:
    commands:
      - export CURRENT_VERSION=$(aws lambda get-alias --function-name dev-function --name development --query 'FunctionVersion' --output text)
      - NEW_VERSION=$((CURRENT_VERSION + 1))
      - export NEW_VERSION
      - zip lambda_function.zip lambda_function.py
  build:
    commands:
      - echo $CURRENT_VERSION
      - echo $NEW_VERSION
      - aws lambda publish-version --function-name dev-function
      - aws lambda update-function-code --function-name dev-function --zip-file fileb://lambda_function.zip
  post_build:
    commands:
      - sed -i "s/1/$CURRENT_VERSION/g" appspec.yaml
      - sed -i "s/2/$NEW_VERSION/g" appspec.yaml
      - cat appspec.yaml

artifacts:
  files:
    - appspec.yaml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'